//Create array of options to be added
var HMR3_optionText = [
    "Please Choose", 
    "Custom URL",
    "Get More Roms",
    "Pokemon Clover (currently not working)", 
    "Pokemon Flora Sky", 
    "Pokemon Leaf Green", 
    "Pokemon Moon Galaxy",
    "Pokemon Dark Worship",
    "Pokemon Emerald Horizions",
    "Pokemon Exceeded",
    "Pokemon LGPika",
    "Pokemon Mirage of Tales",
    "Pokemon PK Theta",
    "Pokemon Elysium",
    "Pokemon Mercury Azoth",
    "Pokemon Ultra Gold Sigma",
    "Pokemon Yuval",
    "Pokemon Re:Verse",
    "Pokemon ROWE",
    "Pokemon Radical Red",
    "Pokemon Ruby Renev",
    "Pokemon Shiron Castle",
    "Pokemon Unknown",
    "Pokemon Crest",
    "Pokemon Nameless",
    "Pokemon Regis' Origin",
    "Pokemon Ash's Quest",
    "Pokemon Ash Grey",
    "Pokemon Battle Final",
    "Pokemon Fire Red",
    "Pokemon Emerald",
    "Pokemon Green",
    "Pokemon Ruby",
    "Pokemon Sapphire",
    "Pokemon Better Than Fire Red",
    "Pokemon Doubles Fire Red",
    "Pokemon Emerald Essence",
    "Pokemon The Teal Mask",
    "Pokemon Thunder Yellow",
    "Pokemon Water Blue",
    "Pokemon 2 Heroes",
    "Pokemon 2050",
    "Pokemon 2 Awesome",
    "Pokemon A Grand Day Out",
    "Pokemon A New Dawn",
    "Pokemon Abandoned Ruby",
    "Pokemon Abra Adventure",
    "Pokemon Accecpt Defeat",
    "Pokemon Adamantite",
    "Pokemon Blue",
    "Pokemon Red Version",
    "Pokemon Yellow Version",
    "Pokemon Baby Blue",
    "Pokemon Celebrations",
    "Pokemon Blueberry",
    "Pokemon Carmine Red",
    "Pokemon Green",
    "Pokemon Kanto Expansion Pack",
    "Pokemon Let's Go Meltan",
    "Pokemon Project Neo",
    "Pokemon Pure Blue",
    "Pokemon Pure Green",
    "Pokemon Pure Red",
    "Pokemon Red Expert",
    "Pokemon Redcurrant",
    "Pokemon Roaming Red",
    "Pokemon Shin Blue",
    "Pokemon Shin Green",
    "Pokemon Shin Red",
    "Pokemon Strike Yellow",
    "Pokemon Yellow Kaizo",
    "Pokemon Yellow Supreme",
    "Kirby Mirror",
    "Pokemon Nightmare In Dreamland",
    "Mario Kart",
    "Mario Pinball",
    "Monopoly"
    
    
];

var HMR3_optionValue = [
    "#", 
    "customlink",
    "moreroms",
    "https://rawcdn.githack.com/moondoges/cyanide/a02ac068975c5383c3d297c531a85eff04fbcfdf/pokemon_clover.gba", //link not working
    "https://rawcdn.githack.com/srojam/gba/58893088e3805baaf716e0af6801aaeeae1a0efb/Binaries/pokemonflorasky.gba", 
    "https://rawcdn.githack.com/srojam/gba/58893088e3805baaf716e0af6801aaeeae1a0efb/Binaries/pokemongreen.gba", 
    "https://rawcdn.githack.com/vbaemulator/GBA-Roms/f8ff9ba91598a5e996f29c7c27342f062faa989d/Pokemon%20Moon%20Galaxy.zip",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Dark%20Worship%20ENGLISH%20COMPLETE.Gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/EmeraldHorizonsv1.09.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Exceeded%20v11.5.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/LGPika%20(v8.0).gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Mirage%20of%20Tales%20(Alpha%20v3.3).gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Odyssey%20Beta%20v2.6.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/PK%20Theta%20EM%20721%20Ex%2027-02-17.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Pokemon%20Elysium_A.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Pokemon%20Mercury%20Azoth%20Project%20(Demo%20v0.011).gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Pokemon%20Ultra%20Shiny%20Gold%20Sigma%20Completo%201.5.0.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/PokemonYuvalVersion.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/RE%20Verse%20v0.9.1.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/ROWE%20(v1.9.4).gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Radical%20Red.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/RubyRenev%20v1.4.2.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Shiron%20Castle%20(v2.0).gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/Unknown%20(v1.0).gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/crest%20v1.0.9.6.3.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/nameless%20v5.30.gba",
    "https://raw.githack.com/TrapjawwS/funnyemulatorjs/main/romhacks/regis'origin.gba",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20Ash's%20Quest.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20AshGray%204.5.3.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20Battle%20Fire%20bfinal.zip",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/pokemonred.gba",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/pokemonemerald.gba",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/pokemongreen.gba",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/pokemonruby.gba",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/pokemonsapphire.gba",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20Better%20than%20Fire%20Red%20v1.1.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20DoublesFireRed%201.1.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20Emerald%20Essence%20v1.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20The%20Teal%20Mask%20GBA%201.0.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20Thunder%20Yellow.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20-%20Water%20Blue.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%202%20Heroes.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%202050%20v0.0.1.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%202Awesome.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20A%20Grand%20Day%20Out.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20A%20New%20Dawn%20v0.2.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20Abandoned%20Ruby.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20Abra%20Adventure%20v1%20(1).zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20Accept%20Defeat%20V2.zip",
    "https://raw.githack.com/vbaemulator/GBA-Roms/main/Pokemon%20Adamantite.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20-%20Blue%20Version%20(USA,%20Europe)%20(SGB%20Enhanced).zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20-%20Red%20Version%20(USA,%20Europe)%20(SGB%20Enhanced).zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20-%20Yellow%20Version%20-%20Special%20Pikachu%20Edition%20(USA,%20Europe)%20(CGB+SGB%20Enhanced).zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Baby%20Blue%20v19-08-23.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Blue%20Celebrations%20v1.8.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Blueberry%20v1.0.18.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Carmine%20Red%20v1.1.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Green%20v3.0%20(English).zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Kanto%20Expansion%20Pak.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Lets%20Go%20Meltan.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Project%20Neo.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20PureBlue%20v2.5.5.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20PureGreen%20v2.5.5.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20PureRed%20v2.5.5.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Red%20Expert%20v1.0.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Redcurrant%20v1.0.18.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Roaming%20Red%20v3.1.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Shin%20Blue%20v1.24.5.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Shin%20Green%20v1.24.5.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Shin%20Red%20v1.24.5.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Strike%20Yellow%20v0.4.zip",
    "https://github.com/vbaemulator/GB-Roms/raw/main/Pokemon%20Strike%20Yellow%20v0.4.zip",
    "https://raw.githack.com/vbaemulator/GB-Roms/main/Pokemon%20Yellow%20Supreme%20v2.0.zip",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/kirbymirror.gba",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/kirbynightmare.gba",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/mariokart.gba",
    "https://raw.githack.com/srojam/gba/gh-pages/Binaries/mariopinball.gba",
    "https://github.com/srojam/gba/raw/gh-pages/Binaries/monopoly.gba"
];
